/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalCasesRouteImport } from './routes/portal.cases'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminClinicsRouteImport } from './routes/admin.clinics'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as MarketingWorkflowRouteImport } from './routes/_marketing.workflow'
import { Route as MarketingTechnologyRouteImport } from './routes/_marketing.technology'
import { Route as MarketingSubmitRouteImport } from './routes/_marketing.submit'
import { Route as MarketingQualityRouteImport } from './routes/_marketing.quality'
import { Route as MarketingContactRouteImport } from './routes/_marketing.contact'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as MarketingServicesIndexRouteImport } from './routes/_marketing.services.index'
import { Route as PortalCasesNewRouteImport } from './routes/portal.cases.new'
import { Route as PortalCasesIdRouteImport } from './routes/portal.cases.$id'
import { Route as AdminPostEditorIdRouteImport } from './routes/admin.post-editor.$id'
import { Route as AdminPageEditorSlugRouteImport } from './routes/admin.page-editor.$slug'
import { Route as MarketingServicesSlugRouteImport } from './routes/_marketing.services.$slug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCasesRoute = PortalCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => PortalRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const MarketingWorkflowRoute = MarketingWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTechnologyRoute = MarketingTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSubmitRoute = MarketingSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingQualityRoute = MarketingQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingServicesIndexRoute = MarketingServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => MarketingRoute,
} as any)
const PortalCasesNewRoute = PortalCasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PortalCasesRoute,
} as any)
const PortalCasesIdRoute = PortalCasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalCasesRoute,
} as any)
const AdminPostEditorIdRoute = AdminPostEditorIdRouteImport.update({
  id: '/post-editor/$id',
  path: '/post-editor/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPageEditorSlugRoute = AdminPageEditorSlugRouteImport.update({
  id: '/page-editor/$slug',
  path: '/page-editor/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const MarketingServicesSlugRoute = MarketingServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/quality': typeof MarketingQualityRoute
  '/submit': typeof MarketingSubmitRoute
  '/technology': typeof MarketingTechnologyRoute
  '/workflow': typeof MarketingWorkflowRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/cases': typeof PortalCasesRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/services/$slug': typeof MarketingServicesSlugRoute
  '/admin/page-editor/$slug': typeof AdminPageEditorSlugRoute
  '/admin/post-editor/$id': typeof AdminPostEditorIdRoute
  '/portal/cases/$id': typeof PortalCasesIdRoute
  '/portal/cases/new': typeof PortalCasesNewRoute
  '/services/': typeof MarketingServicesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/quality': typeof MarketingQualityRoute
  '/submit': typeof MarketingSubmitRoute
  '/technology': typeof MarketingTechnologyRoute
  '/workflow': typeof MarketingWorkflowRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/cases': typeof PortalCasesRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/services/$slug': typeof MarketingServicesSlugRoute
  '/admin/page-editor/$slug': typeof AdminPageEditorSlugRoute
  '/admin/post-editor/$id': typeof AdminPostEditorIdRoute
  '/portal/cases/$id': typeof PortalCasesIdRoute
  '/portal/cases/new': typeof PortalCasesNewRoute
  '/services': typeof MarketingServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/quality': typeof MarketingQualityRoute
  '/_marketing/submit': typeof MarketingSubmitRoute
  '/_marketing/technology': typeof MarketingTechnologyRoute
  '/_marketing/workflow': typeof MarketingWorkflowRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/cases': typeof PortalCasesRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_marketing/services/$slug': typeof MarketingServicesSlugRoute
  '/admin/page-editor/$slug': typeof AdminPageEditorSlugRoute
  '/admin/post-editor/$id': typeof AdminPostEditorIdRoute
  '/portal/cases/$id': typeof PortalCasesIdRoute
  '/portal/cases/new': typeof PortalCasesNewRoute
  '/_marketing/services/': typeof MarketingServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/about'
    | '/contact'
    | '/quality'
    | '/submit'
    | '/technology'
    | '/workflow'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/cases'
    | '/admin/clinics'
    | '/admin/content'
    | '/admin/email-templates'
    | '/admin/finance'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/portal/cases'
    | '/portal/documents'
    | '/portal/messages'
    | '/portal/profile'
    | '/admin/'
    | '/portal/'
    | '/services/$slug'
    | '/admin/page-editor/$slug'
    | '/admin/post-editor/$id'
    | '/portal/cases/$id'
    | '/portal/cases/new'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/about'
    | '/contact'
    | '/quality'
    | '/submit'
    | '/technology'
    | '/workflow'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/cases'
    | '/admin/clinics'
    | '/admin/content'
    | '/admin/email-templates'
    | '/admin/finance'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/portal/cases'
    | '/portal/documents'
    | '/portal/messages'
    | '/portal/profile'
    | '/'
    | '/admin'
    | '/portal'
    | '/services/$slug'
    | '/admin/page-editor/$slug'
    | '/admin/post-editor/$id'
    | '/portal/cases/$id'
    | '/portal/cases/new'
    | '/services'
  id:
    | '__root__'
    | '/_marketing'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/_marketing/about'
    | '/_marketing/contact'
    | '/_marketing/quality'
    | '/_marketing/submit'
    | '/_marketing/technology'
    | '/_marketing/workflow'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/cases'
    | '/admin/clinics'
    | '/admin/content'
    | '/admin/email-templates'
    | '/admin/finance'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/portal/cases'
    | '/portal/documents'
    | '/portal/messages'
    | '/portal/profile'
    | '/_marketing/'
    | '/admin/'
    | '/portal/'
    | '/_marketing/services/$slug'
    | '/admin/page-editor/$slug'
    | '/admin/post-editor/$id'
    | '/portal/cases/$id'
    | '/portal/cases/new'
    | '/_marketing/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cases': {
      id: '/portal/cases'
      path: '/cases'
      fullPath: '/portal/cases'
      preLoaderRoute: typeof PortalCasesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinics': {
      id: '/admin/clinics'
      path: '/clinics'
      fullPath: '/admin/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_marketing/workflow': {
      id: '/_marketing/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof MarketingWorkflowRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/technology': {
      id: '/_marketing/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof MarketingTechnologyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/submit': {
      id: '/_marketing/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof MarketingSubmitRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/quality': {
      id: '/_marketing/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof MarketingQualityRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/services/': {
      id: '/_marketing/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof MarketingServicesIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/portal/cases/new': {
      id: '/portal/cases/new'
      path: '/new'
      fullPath: '/portal/cases/new'
      preLoaderRoute: typeof PortalCasesNewRouteImport
      parentRoute: typeof PortalCasesRoute
    }
    '/portal/cases/$id': {
      id: '/portal/cases/$id'
      path: '/$id'
      fullPath: '/portal/cases/$id'
      preLoaderRoute: typeof PortalCasesIdRouteImport
      parentRoute: typeof PortalCasesRoute
    }
    '/admin/post-editor/$id': {
      id: '/admin/post-editor/$id'
      path: '/post-editor/$id'
      fullPath: '/admin/post-editor/$id'
      preLoaderRoute: typeof AdminPostEditorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/page-editor/$slug': {
      id: '/admin/page-editor/$slug'
      path: '/page-editor/$slug'
      fullPath: '/admin/page-editor/$slug'
      preLoaderRoute: typeof AdminPageEditorSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_marketing/services/$slug': {
      id: '/_marketing/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof MarketingServicesSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingQualityRoute: typeof MarketingQualityRoute
  MarketingSubmitRoute: typeof MarketingSubmitRoute
  MarketingTechnologyRoute: typeof MarketingTechnologyRoute
  MarketingWorkflowRoute: typeof MarketingWorkflowRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingServicesSlugRoute: typeof MarketingServicesSlugRoute
  MarketingServicesIndexRoute: typeof MarketingServicesIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingQualityRoute: MarketingQualityRoute,
  MarketingSubmitRoute: MarketingSubmitRoute,
  MarketingTechnologyRoute: MarketingTechnologyRoute,
  MarketingWorkflowRoute: MarketingWorkflowRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingServicesSlugRoute: MarketingServicesSlugRoute,
  MarketingServicesIndexRoute: MarketingServicesIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCasesRoute: typeof AdminCasesRoute
  AdminClinicsRoute: typeof AdminClinicsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPageEditorSlugRoute: typeof AdminPageEditorSlugRoute
  AdminPostEditorIdRoute: typeof AdminPostEditorIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCasesRoute: AdminCasesRoute,
  AdminClinicsRoute: AdminClinicsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPageEditorSlugRoute: AdminPageEditorSlugRoute,
  AdminPostEditorIdRoute: AdminPostEditorIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalCasesRouteChildren {
  PortalCasesIdRoute: typeof PortalCasesIdRoute
  PortalCasesNewRoute: typeof PortalCasesNewRoute
}

const PortalCasesRouteChildren: PortalCasesRouteChildren = {
  PortalCasesIdRoute: PortalCasesIdRoute,
  PortalCasesNewRoute: PortalCasesNewRoute,
}

const PortalCasesRouteWithChildren = PortalCasesRoute._addFileChildren(
  PortalCasesRouteChildren,
)

interface PortalRouteChildren {
  PortalCasesRoute: typeof PortalCasesRouteWithChildren
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCasesRoute: PortalCasesRouteWithChildren,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
