/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalCasesRouteImport } from './routes/portal.cases'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminClinicsRouteImport } from './routes/admin.clinics'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as MarketingWorkflowRouteImport } from './routes/_marketing.workflow'
import { Route as MarketingTermsOfServiceRouteImport } from './routes/_marketing.terms-of-service'
import { Route as MarketingTechnologyRouteImport } from './routes/_marketing.technology'
import { Route as MarketingSubmitRouteImport } from './routes/_marketing.submit'
import { Route as MarketingResourcesRouteImport } from './routes/_marketing.resources'
import { Route as MarketingQualityRouteImport } from './routes/_marketing.quality'
import { Route as MarketingPrivacyPolicyRouteImport } from './routes/_marketing.privacy-policy'
import { Route as MarketingDataNoticeRouteImport } from './routes/_marketing.data-notice'
import { Route as MarketingContactRouteImport } from './routes/_marketing.contact'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as PortalCasesIndexRouteImport } from './routes/portal.cases.index'
import { Route as AdminCasesIndexRouteImport } from './routes/admin.cases.index'
import { Route as MarketingTechnologyIndexRouteImport } from './routes/_marketing.technology.index'
import { Route as MarketingServicesIndexRouteImport } from './routes/_marketing.services.index'
import { Route as MarketingAboutIndexRouteImport } from './routes/_marketing.about.index'
import { Route as PortalCasesNewRouteImport } from './routes/portal.cases.new'
import { Route as PortalCasesIdRouteImport } from './routes/portal.cases.$id'
import { Route as AdminPostEditorIdRouteImport } from './routes/admin.post-editor.$id'
import { Route as AdminPageEditorSlugRouteImport } from './routes/admin.page-editor.$slug'
import { Route as AdminCasesIdRouteImport } from './routes/admin.cases.$id'
import { Route as MarketingTechnologySlmMetalPrintingRouteImport } from './routes/_marketing.technology.slm-metal-printing'
import { Route as MarketingTechnologySinteringCeramicFiringRouteImport } from './routes/_marketing.technology.sintering-ceramic-firing'
import { Route as MarketingTechnologyScanningDesignRouteImport } from './routes/_marketing.technology.scanning-design'
import { Route as MarketingTechnologyFinishingEquipmentRouteImport } from './routes/_marketing.technology.finishing-equipment'
import { Route as MarketingTechnologyCadCamMillingRouteImport } from './routes/_marketing.technology.cad-cam-milling'
import { Route as MarketingTechnology3dPrintingRouteImport } from './routes/_marketing.technology.3d-printing'
import { Route as MarketingServicesSlugRouteImport } from './routes/_marketing.services.$slug'
import { Route as MarketingAboutWhyPrimeRouteImport } from './routes/_marketing.about.why-prime'
import { Route as MarketingAboutOurLaboratoryRouteImport } from './routes/_marketing.about.our-laboratory'
import { Route as MarketingAboutExportCapabilityRouteImport } from './routes/_marketing.about.export-capability'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCasesRoute = PortalCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => PortalRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const MarketingWorkflowRoute = MarketingWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTermsOfServiceRoute = MarketingTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTechnologyRoute = MarketingTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSubmitRoute = MarketingSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingResourcesRoute = MarketingResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingQualityRoute = MarketingQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyPolicyRoute = MarketingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDataNoticeRoute = MarketingDataNoticeRouteImport.update({
  id: '/data-notice',
  path: '/data-notice',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const PortalCasesIndexRoute = PortalCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalCasesRoute,
} as any)
const AdminCasesIndexRoute = AdminCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCasesRoute,
} as any)
const MarketingTechnologyIndexRoute =
  MarketingTechnologyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MarketingTechnologyRoute,
  } as any)
const MarketingServicesIndexRoute = MarketingServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutIndexRoute = MarketingAboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingAboutRoute,
} as any)
const PortalCasesNewRoute = PortalCasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PortalCasesRoute,
} as any)
const PortalCasesIdRoute = PortalCasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalCasesRoute,
} as any)
const AdminPostEditorIdRoute = AdminPostEditorIdRouteImport.update({
  id: '/post-editor/$id',
  path: '/post-editor/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPageEditorSlugRoute = AdminPageEditorSlugRouteImport.update({
  id: '/page-editor/$slug',
  path: '/page-editor/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesIdRoute = AdminCasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCasesRoute,
} as any)
const MarketingTechnologySlmMetalPrintingRoute =
  MarketingTechnologySlmMetalPrintingRouteImport.update({
    id: '/slm-metal-printing',
    path: '/slm-metal-printing',
    getParentRoute: () => MarketingTechnologyRoute,
  } as any)
const MarketingTechnologySinteringCeramicFiringRoute =
  MarketingTechnologySinteringCeramicFiringRouteImport.update({
    id: '/sintering-ceramic-firing',
    path: '/sintering-ceramic-firing',
    getParentRoute: () => MarketingTechnologyRoute,
  } as any)
const MarketingTechnologyScanningDesignRoute =
  MarketingTechnologyScanningDesignRouteImport.update({
    id: '/scanning-design',
    path: '/scanning-design',
    getParentRoute: () => MarketingTechnologyRoute,
  } as any)
const MarketingTechnologyFinishingEquipmentRoute =
  MarketingTechnologyFinishingEquipmentRouteImport.update({
    id: '/finishing-equipment',
    path: '/finishing-equipment',
    getParentRoute: () => MarketingTechnologyRoute,
  } as any)
const MarketingTechnologyCadCamMillingRoute =
  MarketingTechnologyCadCamMillingRouteImport.update({
    id: '/cad-cam-milling',
    path: '/cad-cam-milling',
    getParentRoute: () => MarketingTechnologyRoute,
  } as any)
const MarketingTechnology3dPrintingRoute =
  MarketingTechnology3dPrintingRouteImport.update({
    id: '/3d-printing',
    path: '/3d-printing',
    getParentRoute: () => MarketingTechnologyRoute,
  } as any)
const MarketingServicesSlugRoute = MarketingServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutWhyPrimeRoute = MarketingAboutWhyPrimeRouteImport.update({
  id: '/why-prime',
  path: '/why-prime',
  getParentRoute: () => MarketingAboutRoute,
} as any)
const MarketingAboutOurLaboratoryRoute =
  MarketingAboutOurLaboratoryRouteImport.update({
    id: '/our-laboratory',
    path: '/our-laboratory',
    getParentRoute: () => MarketingAboutRoute,
  } as any)
const MarketingAboutExportCapabilityRoute =
  MarketingAboutExportCapabilityRouteImport.update({
    id: '/export-capability',
    path: '/export-capability',
    getParentRoute: () => MarketingAboutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof MarketingAboutRouteWithChildren
  '/contact': typeof MarketingContactRoute
  '/data-notice': typeof MarketingDataNoticeRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/quality': typeof MarketingQualityRoute
  '/resources': typeof MarketingResourcesRoute
  '/submit': typeof MarketingSubmitRoute
  '/technology': typeof MarketingTechnologyRouteWithChildren
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/workflow': typeof MarketingWorkflowRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cases': typeof AdminCasesRouteWithChildren
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/cases': typeof PortalCasesRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/about/export-capability': typeof MarketingAboutExportCapabilityRoute
  '/about/our-laboratory': typeof MarketingAboutOurLaboratoryRoute
  '/about/why-prime': typeof MarketingAboutWhyPrimeRoute
  '/services/$slug': typeof MarketingServicesSlugRoute
  '/technology/3d-printing': typeof MarketingTechnology3dPrintingRoute
  '/technology/cad-cam-milling': typeof MarketingTechnologyCadCamMillingRoute
  '/technology/finishing-equipment': typeof MarketingTechnologyFinishingEquipmentRoute
  '/technology/scanning-design': typeof MarketingTechnologyScanningDesignRoute
  '/technology/sintering-ceramic-firing': typeof MarketingTechnologySinteringCeramicFiringRoute
  '/technology/slm-metal-printing': typeof MarketingTechnologySlmMetalPrintingRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/admin/page-editor/$slug': typeof AdminPageEditorSlugRoute
  '/admin/post-editor/$id': typeof AdminPostEditorIdRoute
  '/portal/cases/$id': typeof PortalCasesIdRoute
  '/portal/cases/new': typeof PortalCasesNewRoute
  '/about/': typeof MarketingAboutIndexRoute
  '/services/': typeof MarketingServicesIndexRoute
  '/technology/': typeof MarketingTechnologyIndexRoute
  '/admin/cases/': typeof AdminCasesIndexRoute
  '/portal/cases/': typeof PortalCasesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/contact': typeof MarketingContactRoute
  '/data-notice': typeof MarketingDataNoticeRoute
  '/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/quality': typeof MarketingQualityRoute
  '/resources': typeof MarketingResourcesRoute
  '/submit': typeof MarketingSubmitRoute
  '/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/workflow': typeof MarketingWorkflowRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/about/export-capability': typeof MarketingAboutExportCapabilityRoute
  '/about/our-laboratory': typeof MarketingAboutOurLaboratoryRoute
  '/about/why-prime': typeof MarketingAboutWhyPrimeRoute
  '/services/$slug': typeof MarketingServicesSlugRoute
  '/technology/3d-printing': typeof MarketingTechnology3dPrintingRoute
  '/technology/cad-cam-milling': typeof MarketingTechnologyCadCamMillingRoute
  '/technology/finishing-equipment': typeof MarketingTechnologyFinishingEquipmentRoute
  '/technology/scanning-design': typeof MarketingTechnologyScanningDesignRoute
  '/technology/sintering-ceramic-firing': typeof MarketingTechnologySinteringCeramicFiringRoute
  '/technology/slm-metal-printing': typeof MarketingTechnologySlmMetalPrintingRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/admin/page-editor/$slug': typeof AdminPageEditorSlugRoute
  '/admin/post-editor/$id': typeof AdminPostEditorIdRoute
  '/portal/cases/$id': typeof PortalCasesIdRoute
  '/portal/cases/new': typeof PortalCasesNewRoute
  '/about': typeof MarketingAboutIndexRoute
  '/services': typeof MarketingServicesIndexRoute
  '/technology': typeof MarketingTechnologyIndexRoute
  '/admin/cases': typeof AdminCasesIndexRoute
  '/portal/cases': typeof PortalCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_marketing/about': typeof MarketingAboutRouteWithChildren
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/data-notice': typeof MarketingDataNoticeRoute
  '/_marketing/privacy-policy': typeof MarketingPrivacyPolicyRoute
  '/_marketing/quality': typeof MarketingQualityRoute
  '/_marketing/resources': typeof MarketingResourcesRoute
  '/_marketing/submit': typeof MarketingSubmitRoute
  '/_marketing/technology': typeof MarketingTechnologyRouteWithChildren
  '/_marketing/terms-of-service': typeof MarketingTermsOfServiceRoute
  '/_marketing/workflow': typeof MarketingWorkflowRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cases': typeof AdminCasesRouteWithChildren
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/portal/cases': typeof PortalCasesRouteWithChildren
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/profile': typeof PortalProfileRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_marketing/about/export-capability': typeof MarketingAboutExportCapabilityRoute
  '/_marketing/about/our-laboratory': typeof MarketingAboutOurLaboratoryRoute
  '/_marketing/about/why-prime': typeof MarketingAboutWhyPrimeRoute
  '/_marketing/services/$slug': typeof MarketingServicesSlugRoute
  '/_marketing/technology/3d-printing': typeof MarketingTechnology3dPrintingRoute
  '/_marketing/technology/cad-cam-milling': typeof MarketingTechnologyCadCamMillingRoute
  '/_marketing/technology/finishing-equipment': typeof MarketingTechnologyFinishingEquipmentRoute
  '/_marketing/technology/scanning-design': typeof MarketingTechnologyScanningDesignRoute
  '/_marketing/technology/sintering-ceramic-firing': typeof MarketingTechnologySinteringCeramicFiringRoute
  '/_marketing/technology/slm-metal-printing': typeof MarketingTechnologySlmMetalPrintingRoute
  '/admin/cases/$id': typeof AdminCasesIdRoute
  '/admin/page-editor/$slug': typeof AdminPageEditorSlugRoute
  '/admin/post-editor/$id': typeof AdminPostEditorIdRoute
  '/portal/cases/$id': typeof PortalCasesIdRoute
  '/portal/cases/new': typeof PortalCasesNewRoute
  '/_marketing/about/': typeof MarketingAboutIndexRoute
  '/_marketing/services/': typeof MarketingServicesIndexRoute
  '/_marketing/technology/': typeof MarketingTechnologyIndexRoute
  '/admin/cases/': typeof AdminCasesIndexRoute
  '/portal/cases/': typeof PortalCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/about'
    | '/contact'
    | '/data-notice'
    | '/privacy-policy'
    | '/quality'
    | '/resources'
    | '/submit'
    | '/technology'
    | '/terms-of-service'
    | '/workflow'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/cases'
    | '/admin/clinics'
    | '/admin/content'
    | '/admin/email-templates'
    | '/admin/finance'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/portal/cases'
    | '/portal/documents'
    | '/portal/messages'
    | '/portal/profile'
    | '/admin/'
    | '/portal/'
    | '/about/export-capability'
    | '/about/our-laboratory'
    | '/about/why-prime'
    | '/services/$slug'
    | '/technology/3d-printing'
    | '/technology/cad-cam-milling'
    | '/technology/finishing-equipment'
    | '/technology/scanning-design'
    | '/technology/sintering-ceramic-firing'
    | '/technology/slm-metal-printing'
    | '/admin/cases/$id'
    | '/admin/page-editor/$slug'
    | '/admin/post-editor/$id'
    | '/portal/cases/$id'
    | '/portal/cases/new'
    | '/about/'
    | '/services/'
    | '/technology/'
    | '/admin/cases/'
    | '/portal/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/contact'
    | '/data-notice'
    | '/privacy-policy'
    | '/quality'
    | '/resources'
    | '/submit'
    | '/terms-of-service'
    | '/workflow'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/clinics'
    | '/admin/content'
    | '/admin/email-templates'
    | '/admin/finance'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/portal/documents'
    | '/portal/messages'
    | '/portal/profile'
    | '/'
    | '/admin'
    | '/portal'
    | '/about/export-capability'
    | '/about/our-laboratory'
    | '/about/why-prime'
    | '/services/$slug'
    | '/technology/3d-printing'
    | '/technology/cad-cam-milling'
    | '/technology/finishing-equipment'
    | '/technology/scanning-design'
    | '/technology/sintering-ceramic-firing'
    | '/technology/slm-metal-printing'
    | '/admin/cases/$id'
    | '/admin/page-editor/$slug'
    | '/admin/post-editor/$id'
    | '/portal/cases/$id'
    | '/portal/cases/new'
    | '/about'
    | '/services'
    | '/technology'
    | '/admin/cases'
    | '/portal/cases'
  id:
    | '__root__'
    | '/_marketing'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/_marketing/about'
    | '/_marketing/contact'
    | '/_marketing/data-notice'
    | '/_marketing/privacy-policy'
    | '/_marketing/quality'
    | '/_marketing/resources'
    | '/_marketing/submit'
    | '/_marketing/technology'
    | '/_marketing/terms-of-service'
    | '/_marketing/workflow'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/cases'
    | '/admin/clinics'
    | '/admin/content'
    | '/admin/email-templates'
    | '/admin/finance'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/posts'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/portal/cases'
    | '/portal/documents'
    | '/portal/messages'
    | '/portal/profile'
    | '/_marketing/'
    | '/admin/'
    | '/portal/'
    | '/_marketing/about/export-capability'
    | '/_marketing/about/our-laboratory'
    | '/_marketing/about/why-prime'
    | '/_marketing/services/$slug'
    | '/_marketing/technology/3d-printing'
    | '/_marketing/technology/cad-cam-milling'
    | '/_marketing/technology/finishing-equipment'
    | '/_marketing/technology/scanning-design'
    | '/_marketing/technology/sintering-ceramic-firing'
    | '/_marketing/technology/slm-metal-printing'
    | '/admin/cases/$id'
    | '/admin/page-editor/$slug'
    | '/admin/post-editor/$id'
    | '/portal/cases/$id'
    | '/portal/cases/new'
    | '/_marketing/about/'
    | '/_marketing/services/'
    | '/_marketing/technology/'
    | '/admin/cases/'
    | '/portal/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cases': {
      id: '/portal/cases'
      path: '/cases'
      fullPath: '/portal/cases'
      preLoaderRoute: typeof PortalCasesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinics': {
      id: '/admin/clinics'
      path: '/clinics'
      fullPath: '/admin/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_marketing/workflow': {
      id: '/_marketing/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof MarketingWorkflowRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/terms-of-service': {
      id: '/_marketing/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof MarketingTermsOfServiceRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/technology': {
      id: '/_marketing/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof MarketingTechnologyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/submit': {
      id: '/_marketing/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof MarketingSubmitRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/resources': {
      id: '/_marketing/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof MarketingResourcesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/quality': {
      id: '/_marketing/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof MarketingQualityRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy-policy': {
      id: '/_marketing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof MarketingPrivacyPolicyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/data-notice': {
      id: '/_marketing/data-notice'
      path: '/data-notice'
      fullPath: '/data-notice'
      preLoaderRoute: typeof MarketingDataNoticeRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/portal/cases/': {
      id: '/portal/cases/'
      path: '/'
      fullPath: '/portal/cases/'
      preLoaderRoute: typeof PortalCasesIndexRouteImport
      parentRoute: typeof PortalCasesRoute
    }
    '/admin/cases/': {
      id: '/admin/cases/'
      path: '/'
      fullPath: '/admin/cases/'
      preLoaderRoute: typeof AdminCasesIndexRouteImport
      parentRoute: typeof AdminCasesRoute
    }
    '/_marketing/technology/': {
      id: '/_marketing/technology/'
      path: '/'
      fullPath: '/technology/'
      preLoaderRoute: typeof MarketingTechnologyIndexRouteImport
      parentRoute: typeof MarketingTechnologyRoute
    }
    '/_marketing/services/': {
      id: '/_marketing/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof MarketingServicesIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about/': {
      id: '/_marketing/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof MarketingAboutIndexRouteImport
      parentRoute: typeof MarketingAboutRoute
    }
    '/portal/cases/new': {
      id: '/portal/cases/new'
      path: '/new'
      fullPath: '/portal/cases/new'
      preLoaderRoute: typeof PortalCasesNewRouteImport
      parentRoute: typeof PortalCasesRoute
    }
    '/portal/cases/$id': {
      id: '/portal/cases/$id'
      path: '/$id'
      fullPath: '/portal/cases/$id'
      preLoaderRoute: typeof PortalCasesIdRouteImport
      parentRoute: typeof PortalCasesRoute
    }
    '/admin/post-editor/$id': {
      id: '/admin/post-editor/$id'
      path: '/post-editor/$id'
      fullPath: '/admin/post-editor/$id'
      preLoaderRoute: typeof AdminPostEditorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/page-editor/$slug': {
      id: '/admin/page-editor/$slug'
      path: '/page-editor/$slug'
      fullPath: '/admin/page-editor/$slug'
      preLoaderRoute: typeof AdminPageEditorSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases/$id': {
      id: '/admin/cases/$id'
      path: '/$id'
      fullPath: '/admin/cases/$id'
      preLoaderRoute: typeof AdminCasesIdRouteImport
      parentRoute: typeof AdminCasesRoute
    }
    '/_marketing/technology/slm-metal-printing': {
      id: '/_marketing/technology/slm-metal-printing'
      path: '/slm-metal-printing'
      fullPath: '/technology/slm-metal-printing'
      preLoaderRoute: typeof MarketingTechnologySlmMetalPrintingRouteImport
      parentRoute: typeof MarketingTechnologyRoute
    }
    '/_marketing/technology/sintering-ceramic-firing': {
      id: '/_marketing/technology/sintering-ceramic-firing'
      path: '/sintering-ceramic-firing'
      fullPath: '/technology/sintering-ceramic-firing'
      preLoaderRoute: typeof MarketingTechnologySinteringCeramicFiringRouteImport
      parentRoute: typeof MarketingTechnologyRoute
    }
    '/_marketing/technology/scanning-design': {
      id: '/_marketing/technology/scanning-design'
      path: '/scanning-design'
      fullPath: '/technology/scanning-design'
      preLoaderRoute: typeof MarketingTechnologyScanningDesignRouteImport
      parentRoute: typeof MarketingTechnologyRoute
    }
    '/_marketing/technology/finishing-equipment': {
      id: '/_marketing/technology/finishing-equipment'
      path: '/finishing-equipment'
      fullPath: '/technology/finishing-equipment'
      preLoaderRoute: typeof MarketingTechnologyFinishingEquipmentRouteImport
      parentRoute: typeof MarketingTechnologyRoute
    }
    '/_marketing/technology/cad-cam-milling': {
      id: '/_marketing/technology/cad-cam-milling'
      path: '/cad-cam-milling'
      fullPath: '/technology/cad-cam-milling'
      preLoaderRoute: typeof MarketingTechnologyCadCamMillingRouteImport
      parentRoute: typeof MarketingTechnologyRoute
    }
    '/_marketing/technology/3d-printing': {
      id: '/_marketing/technology/3d-printing'
      path: '/3d-printing'
      fullPath: '/technology/3d-printing'
      preLoaderRoute: typeof MarketingTechnology3dPrintingRouteImport
      parentRoute: typeof MarketingTechnologyRoute
    }
    '/_marketing/services/$slug': {
      id: '/_marketing/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof MarketingServicesSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about/why-prime': {
      id: '/_marketing/about/why-prime'
      path: '/why-prime'
      fullPath: '/about/why-prime'
      preLoaderRoute: typeof MarketingAboutWhyPrimeRouteImport
      parentRoute: typeof MarketingAboutRoute
    }
    '/_marketing/about/our-laboratory': {
      id: '/_marketing/about/our-laboratory'
      path: '/our-laboratory'
      fullPath: '/about/our-laboratory'
      preLoaderRoute: typeof MarketingAboutOurLaboratoryRouteImport
      parentRoute: typeof MarketingAboutRoute
    }
    '/_marketing/about/export-capability': {
      id: '/_marketing/about/export-capability'
      path: '/export-capability'
      fullPath: '/about/export-capability'
      preLoaderRoute: typeof MarketingAboutExportCapabilityRouteImport
      parentRoute: typeof MarketingAboutRoute
    }
  }
}

interface MarketingAboutRouteChildren {
  MarketingAboutExportCapabilityRoute: typeof MarketingAboutExportCapabilityRoute
  MarketingAboutOurLaboratoryRoute: typeof MarketingAboutOurLaboratoryRoute
  MarketingAboutWhyPrimeRoute: typeof MarketingAboutWhyPrimeRoute
  MarketingAboutIndexRoute: typeof MarketingAboutIndexRoute
}

const MarketingAboutRouteChildren: MarketingAboutRouteChildren = {
  MarketingAboutExportCapabilityRoute: MarketingAboutExportCapabilityRoute,
  MarketingAboutOurLaboratoryRoute: MarketingAboutOurLaboratoryRoute,
  MarketingAboutWhyPrimeRoute: MarketingAboutWhyPrimeRoute,
  MarketingAboutIndexRoute: MarketingAboutIndexRoute,
}

const MarketingAboutRouteWithChildren = MarketingAboutRoute._addFileChildren(
  MarketingAboutRouteChildren,
)

interface MarketingTechnologyRouteChildren {
  MarketingTechnology3dPrintingRoute: typeof MarketingTechnology3dPrintingRoute
  MarketingTechnologyCadCamMillingRoute: typeof MarketingTechnologyCadCamMillingRoute
  MarketingTechnologyFinishingEquipmentRoute: typeof MarketingTechnologyFinishingEquipmentRoute
  MarketingTechnologyScanningDesignRoute: typeof MarketingTechnologyScanningDesignRoute
  MarketingTechnologySinteringCeramicFiringRoute: typeof MarketingTechnologySinteringCeramicFiringRoute
  MarketingTechnologySlmMetalPrintingRoute: typeof MarketingTechnologySlmMetalPrintingRoute
  MarketingTechnologyIndexRoute: typeof MarketingTechnologyIndexRoute
}

const MarketingTechnologyRouteChildren: MarketingTechnologyRouteChildren = {
  MarketingTechnology3dPrintingRoute: MarketingTechnology3dPrintingRoute,
  MarketingTechnologyCadCamMillingRoute: MarketingTechnologyCadCamMillingRoute,
  MarketingTechnologyFinishingEquipmentRoute:
    MarketingTechnologyFinishingEquipmentRoute,
  MarketingTechnologyScanningDesignRoute:
    MarketingTechnologyScanningDesignRoute,
  MarketingTechnologySinteringCeramicFiringRoute:
    MarketingTechnologySinteringCeramicFiringRoute,
  MarketingTechnologySlmMetalPrintingRoute:
    MarketingTechnologySlmMetalPrintingRoute,
  MarketingTechnologyIndexRoute: MarketingTechnologyIndexRoute,
}

const MarketingTechnologyRouteWithChildren =
  MarketingTechnologyRoute._addFileChildren(MarketingTechnologyRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRouteWithChildren
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingDataNoticeRoute: typeof MarketingDataNoticeRoute
  MarketingPrivacyPolicyRoute: typeof MarketingPrivacyPolicyRoute
  MarketingQualityRoute: typeof MarketingQualityRoute
  MarketingResourcesRoute: typeof MarketingResourcesRoute
  MarketingSubmitRoute: typeof MarketingSubmitRoute
  MarketingTechnologyRoute: typeof MarketingTechnologyRouteWithChildren
  MarketingTermsOfServiceRoute: typeof MarketingTermsOfServiceRoute
  MarketingWorkflowRoute: typeof MarketingWorkflowRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingServicesSlugRoute: typeof MarketingServicesSlugRoute
  MarketingServicesIndexRoute: typeof MarketingServicesIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRouteWithChildren,
  MarketingContactRoute: MarketingContactRoute,
  MarketingDataNoticeRoute: MarketingDataNoticeRoute,
  MarketingPrivacyPolicyRoute: MarketingPrivacyPolicyRoute,
  MarketingQualityRoute: MarketingQualityRoute,
  MarketingResourcesRoute: MarketingResourcesRoute,
  MarketingSubmitRoute: MarketingSubmitRoute,
  MarketingTechnologyRoute: MarketingTechnologyRouteWithChildren,
  MarketingTermsOfServiceRoute: MarketingTermsOfServiceRoute,
  MarketingWorkflowRoute: MarketingWorkflowRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingServicesSlugRoute: MarketingServicesSlugRoute,
  MarketingServicesIndexRoute: MarketingServicesIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface AdminCasesRouteChildren {
  AdminCasesIdRoute: typeof AdminCasesIdRoute
  AdminCasesIndexRoute: typeof AdminCasesIndexRoute
}

const AdminCasesRouteChildren: AdminCasesRouteChildren = {
  AdminCasesIdRoute: AdminCasesIdRoute,
  AdminCasesIndexRoute: AdminCasesIndexRoute,
}

const AdminCasesRouteWithChildren = AdminCasesRoute._addFileChildren(
  AdminCasesRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCasesRoute: typeof AdminCasesRouteWithChildren
  AdminClinicsRoute: typeof AdminClinicsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPageEditorSlugRoute: typeof AdminPageEditorSlugRoute
  AdminPostEditorIdRoute: typeof AdminPostEditorIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCasesRoute: AdminCasesRouteWithChildren,
  AdminClinicsRoute: AdminClinicsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPageEditorSlugRoute: AdminPageEditorSlugRoute,
  AdminPostEditorIdRoute: AdminPostEditorIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalCasesRouteChildren {
  PortalCasesIdRoute: typeof PortalCasesIdRoute
  PortalCasesNewRoute: typeof PortalCasesNewRoute
  PortalCasesIndexRoute: typeof PortalCasesIndexRoute
}

const PortalCasesRouteChildren: PortalCasesRouteChildren = {
  PortalCasesIdRoute: PortalCasesIdRoute,
  PortalCasesNewRoute: PortalCasesNewRoute,
  PortalCasesIndexRoute: PortalCasesIndexRoute,
}

const PortalCasesRouteWithChildren = PortalCasesRoute._addFileChildren(
  PortalCasesRouteChildren,
)

interface PortalRouteChildren {
  PortalCasesRoute: typeof PortalCasesRouteWithChildren
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCasesRoute: PortalCasesRouteWithChildren,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
